management:
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librairy
    username: librairy_user
    password: password
  jooq:
    sql-dialect: mysql
  flyway:
    url: jdbc:mysql://localhost:3306/librairy
    user: librairy_deploy_user
    password: password